coverage:
  status:
    patch:
      default:
        # basic
        target: 80%
        threshold: 1%
        base: auto 
        flags: 
          - unit
        paths: 
          - "pyvts"
       # advanced settings
        branches: 
          - main
        if_ci_failed: error  #success, failure, error, ignore
        informational: false
        only_pulls: false