coverage:
  status:
    project:
      default:
        # basic
        target: 50%
        threshold: 0%
        base: auto 
        flags: 
          - unit
        paths: 
          - "pyvts"
       # advanced settings
        branches: 
          - main
        if_ci_failed: error  #success, failure, error, ignore
        informational: false
        only_pulls: false